# Site settings
title: IronCorn
email: youremailaddress@gmail.com
description: We believe that games are a window to our imagination and a path to times filled with joy. We use our work to prove so.
As a new company created by 2 friends, our wish is to fulfill our dreams of how games should be. Our aim is to create quality games and meet the expectations of our players by listening to what they want, what we players want.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ironcorn.tech" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/company/ironcorn
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
