# Site settings
title: IronCorn
email: youremailaddress@gmail.com
description: We believe that games are a window to our imagination and a path to times filled with joy. We use our work to prove so.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ironcorn.tech" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
